---
- name: Include {{ pki_method }} CA variables
  include_vars:
    file: "{{ pki_method ~ '_ca.yml' }}"

- name: Install certificate authorities
  include_tasks: "{{ pki_method }}/install_ca.yml"
  when: pki_install_ca | length > 0