# when the created CA certificates are changed
- name: ca cert changed
  meta: noop
  when: false

# when the created server certificates are changed
- name: cert changed
  meta: noop
  when: false

# when a certificate is installed onto a server
- name: cert installed
  meta: noop
  when: false